In [1]:
import polars as pl
import numpy as np

In [2]:
# Cargar datos preparados tras el proceso de limpieza y EDA
df = pl.read_parquet("../data/modeling/base_modelado.parquet")

print(f"Filas: {df.height:,}")
print(f"Columnas: {df.width}")

df.head()

Filas: 40,521,392
Columnas: 24

shape: (5, 24)
┌───────────┬────────────┬──────┬───────────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ id_sensor ┆ id_fecha   ┆ hora ┆ intensidad_me ┆ … ┆ tipo_elem ┆ distrito ┆ latitud   ┆ longitud  │
│ ---       ┆ ---        ┆ ---  ┆ dia           ┆   ┆ ---       ┆ ---      ┆ ---       ┆ ---       │
│ i32       ┆ date       ┆ i32  ┆ ---           ┆   ┆ str       ┆ i32      ┆ f64       ┆ f64       │
│           ┆            ┆      ┆ f64           ┆   ┆           ┆          ┆           ┆           │
╞═══════════╪════════════╪══════╪═══════════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 1001      ┆ 2026-04-18 ┆ 2    ┆ 0.0           ┆ … ┆ other     ┆ 10       ┆ 40.409729 ┆ -3.740786 │
│ 1001      ┆ 2026-04-21 ┆ 2    ┆ 0.0           ┆ … ┆ other     ┆ 10       ┆ 40.409729 ┆ -3.740786 │
│ 1001      ┆ 2026-04-21 ┆ 6    ┆ 0.0           ┆ … ┆ other     ┆ 10       ┆ 40.409729 ┆ -3.740786 │
│ 1002      ┆ 2026-04-16 ┆ 10   ┆ 0.0           ┆ … ┆ other     ┆ 10       ┆ 40.40803  ┆ -3.74376  │
│ 1002      ┆ 2026-04-17 ┆ 21   ┆ 0.0           ┆ … ┆ other     ┆ 10       ┆ 40.40803  ┆ -3.74376  │
└───────────┴────────────┴──────┴───────────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [3]:
df.schema

Schema([('id_sensor', Int32),
        ('id_fecha', Date),
        ('hora', Int32),
        ('intensidad_media', Float64),
        ('intensidad_max', Float64),
        ('intensidad_min', Float64),
        ('ocupacion_media', Float64),
        ('ocupacion_max', Float64),
        ('velocidad_media', Float64),
        ('velocidad_min', Float64),
        ('num_mediciones', Int64),
        ('num_error_E', Float64),
        ('porcentaje_calidad', Float64),
        ('año', Int64),
        ('mes', Int64),
        ('nombre_mes', String),
        ('trimestre', Int64),
        ('dia', Int64),
        ('dia_semana', Int64),
        ('fin_semana', Boolean),
        ('tipo_elem', String),
        ('distrito', Int32),
        ('latitud', Float64),
        ('longitud', Float64)])

In [4]:
df.describe()

shape: (9, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ id_sensor ┆ id_fecha  ┆ hora      ┆ … ┆ tipo_elem ┆ distrito  ┆ latitud   ┆ longitud │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ str       ┆ f64       ┆   ┆ str       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 4.0521392 ┆ 40521392  ┆ 4.0521392 ┆ … ┆ 40521392  ┆ 4.0521392 ┆ 4.0521392 ┆ 4.052139 │
│           ┆ e7        ┆           ┆ e7        ┆   ┆           ┆ e7        ┆ e7        ┆ 2e7      │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0.0       ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 6794.1558 ┆ 2025-12-3 ┆ 11.520612 ┆ … ┆ null      ┆ 10.287664 ┆ 40.430422 ┆ -3.68403 │
│           ┆ 99        ┆ 0 16:06:5 ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆           ┆ 6.105902  ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 2677.6982 ┆ null      ┆ 6.917672  ┆ … ┆ null      ┆ 5.38041   ┆ 0.038802  ┆ 0.042648 │
│           ┆ 22        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1001.0    ┆ 2025-07-0 ┆ 0.0       ┆ … ┆ M30       ┆ 0.0       ┆ 40.332454 ┆ -3.83688 │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ 25%       ┆ 4693.0    ┆ 2025-09-3 ┆ 6.0       ┆ … ┆ null      ┆ 6.0       ┆ 40.39921  ┆ -3.71253 │
│           ┆           ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ 50%       ┆ 5989.0    ┆ 2025-12-3 ┆ 12.0      ┆ … ┆ null      ┆ 10.0      ┆ 40.43189  ┆ -3.68692 │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 10111.0   ┆ 2026-04-0 ┆ 18.0      ┆ … ┆ null      ┆ 15.0      ┆ 40.459606 ┆ -3.65648 │
│           ┆           ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ max       ┆ 11541.0   ┆ 2026-06-3 ┆ 23.0      ┆ … ┆ other     ┆ 21.0      ┆ 40.515611 ┆ -3.55162 │
│           ┆           ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ 3        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df = (
    df.with_columns(
        pl.datetime(
            year=pl.col("id_fecha").dt.year(),
            month=pl.col("id_fecha").dt.month(),
            day=pl.col("id_fecha").dt.day(),
            hour=pl.col("hora"),
            minute=pl.lit(0),
            second=pl.lit(0),
        ).alias("fecha_hora")
    )
    .sort(["id_sensor", "fecha_hora"])
)

In [6]:
df.select(
    [
        "id_sensor",
        "id_fecha",
        "hora",
        "fecha_hora",
    ]
).head(10)

shape: (10, 4)
┌───────────┬────────────┬──────┬─────────────────────┐
│ id_sensor ┆ id_fecha   ┆ hora ┆ fecha_hora          │
│ ---       ┆ ---        ┆ ---  ┆ ---                 │
│ i32       ┆ date       ┆ i32  ┆ datetime[μs]        │
╞═══════════╪════════════╪══════╪═════════════════════╡
│ 1001      ┆ 2026-03-04 ┆ 13   ┆ 2026-03-04 13:00:00 │
│ 1001      ┆ 2026-03-04 ┆ 14   ┆ 2026-03-04 14:00:00 │
│ 1001      ┆ 2026-03-04 ┆ 15   ┆ 2026-03-04 15:00:00 │
│ 1001      ┆ 2026-03-04 ┆ 16   ┆ 2026-03-04 16:00:00 │
│ 1001      ┆ 2026-03-04 ┆ 17   ┆ 2026-03-04 17:00:00 │
│ 1001      ┆ 2026-03-04 ┆ 18   ┆ 2026-03-04 18:00:00 │
│ 1001      ┆ 2026-03-04 ┆ 19   ┆ 2026-03-04 19:00:00 │
│ 1001      ┆ 2026-03-04 ┆ 20   ┆ 2026-03-04 20:00:00 │
│ 1001      ┆ 2026-03-04 ┆ 21   ┆ 2026-03-04 21:00:00 │
│ 1001      ┆ 2026-03-04 ┆ 22   ┆ 2026-03-04 22:00:00 │
└───────────┴────────────┴──────┴─────────────────────┘

In [7]:
(
    df
    .group_by("id_sensor")
    .agg(
        [
            pl.col("fecha_hora").min().alias("inicio"),
            pl.col("fecha_hora").max().alias("fin"),
            pl.len().alias("registros"),
        ]
    )
    .head()
)

shape: (5, 4)
┌───────────┬─────────────────────┬─────────────────────┬───────────┐
│ id_sensor ┆ inicio              ┆ fin                 ┆ registros │
│ ---       ┆ ---                 ┆ ---                 ┆ ---       │
│ i32       ┆ datetime[μs]        ┆ datetime[μs]        ┆ u32       │
╞═══════════╪═════════════════════╪═════════════════════╪═══════════╡
│ 1001      ┆ 2026-03-04 13:00:00 ┆ 2026-06-17 01:00:00 ┆ 1854      │
│ 1002      ┆ 2026-03-04 13:00:00 ┆ 2026-06-17 01:00:00 ┆ 1854      │
│ 1003      ┆ 2026-03-04 13:00:00 ┆ 2026-06-17 01:00:00 ┆ 1854      │
│ 1006      ┆ 2025-07-01 00:00:00 ┆ 2026-06-30 23:00:00 ┆ 7979      │
│ 1009      ┆ 2025-09-25 09:00:00 ┆ 2026-05-26 13:00:00 ┆ 5081      │
└───────────┴─────────────────────┴─────────────────────┴───────────┘

In [8]:
df = df.with_columns(
    pl.col("fecha_hora")
    .diff()
    .over("id_sensor")
    .alias("delta_tiempo")
)

In [9]:
(
    df
    .group_by("delta_tiempo")
    .len()
    .sort("delta_tiempo")
)

shape: (703, 2)
┌──────────────┬──────────┐
│ delta_tiempo ┆ len      │
│ ---          ┆ ---      │
│ duration[μs] ┆ u32      │
╞══════════════╪══════════╡
│ null         ┆ 4933     │
│ 1h           ┆ 40384131 │
│ 2h           ┆ 56185    │
│ 3h           ┆ 21554    │
│ 4h           ┆ 9218     │
│ …            ┆ …        │
│ 169d 5h      ┆ 1        │
│ 171d 17h     ┆ 1        │
│ 173d 12h     ┆ 1        │
│ 174d         ┆ 1        │
│ 223d 6h      ┆ 3        │
└──────────────┴──────────┘

In [10]:
huecos = (
    df
    .filter(
        (pl.col("delta_tiempo").is_not_null()) &
        (pl.col("delta_tiempo") != pl.duration(hours=1))
    )
)

print(f"Registros con saltos temporales: {huecos.height:,}")

Registros con saltos temporales: 132,328

In [11]:
huecos.select(
    [
        "id_sensor",
        "fecha_hora",
        "delta_tiempo",
    ]
).head(20)

shape: (20, 3)
┌───────────┬─────────────────────┬──────────────┐
│ id_sensor ┆ fecha_hora          ┆ delta_tiempo │
│ ---       ┆ ---                 ┆ ---          │
│ i32       ┆ datetime[μs]        ┆ duration[μs] │
╞═══════════╪═════════════════════╪══════════════╡
│ 1001      ┆ 2026-04-16 09:00:00 ┆ 27d 8h       │
│ 1002      ┆ 2026-04-16 09:00:00 ┆ 27d 8h       │
│ 1003      ┆ 2026-04-16 09:00:00 ┆ 27d 8h       │
│ 1006      ┆ 2025-07-24 07:00:00 ┆ 4d 22h       │
│ 1006      ┆ 2025-07-25 05:00:00 ┆ 4h           │
│ …         ┆ …                   ┆ …            │
│ 1006      ┆ 2025-09-26 08:00:00 ┆ 7h           │
│ 1006      ┆ 2025-10-10 03:00:00 ┆ 2h           │
│ 1006      ┆ 2025-11-12 20:00:00 ┆ 6h           │
│ 1006      ┆ 2025-12-19 08:00:00 ┆ 7h           │
│ 1006      ┆ 2025-12-24 00:00:00 ┆ 2h           │
└───────────┴─────────────────────┴──────────────┘

In [12]:
df = df.drop("delta_tiempo")

In [13]:
duplicados = (
    df
    .group_by(["id_sensor", "fecha_hora"])
    .len()
    .filter(pl.col("len") > 1)
)

print(f"Duplicados encontrados: {duplicados.height}")

Duplicados encontrados: 0

In [14]:
print("=" * 50)
print("PREPARACIÓN COMPLETADA")
print("=" * 50)

print(f"Filas: {df.height:,}")
print(f"Columnas: {df.width:,}")
print(f"Sensores únicos: {df['id_sensor'].n_unique():,}")

==================================================
PREPARACIÓN COMPLETADA
==================================================
Filas: 40,521,392
Columnas: 25
Sensores únicos: 4,933

In [15]:
# Transformación cíclica de variables temporales

df = df.with_columns([
    (2 * np.pi * pl.col("hora") / 24).sin().alias("hora_sin"),
    (2 * np.pi * pl.col("hora") / 24).cos().alias("hora_cos"),

    (2 * np.pi * pl.col("dia_semana") / 7).sin().alias("dia_semana_sin"),
    (2 * np.pi * pl.col("dia_semana") / 7).cos().alias("dia_semana_cos"),

    (2 * np.pi * pl.col("mes") / 12).sin().alias("mes_sin"),
    (2 * np.pi * pl.col("mes") / 12).cos().alias("mes_cos"),
])

In [16]:
df.select([
    "hora",
    "hora_sin",
    "hora_cos"
]).head()

shape: (5, 3)
┌──────┬───────────┬───────────┐
│ hora ┆ hora_sin  ┆ hora_cos  │
│ ---  ┆ ---       ┆ ---       │
│ i32  ┆ f64       ┆ f64       │
╞══════╪═══════════╪═══════════╡
│ 13   ┆ -0.258819 ┆ -0.965926 │
│ 14   ┆ -0.5      ┆ -0.866025 │
│ 15   ┆ -0.707107 ┆ -0.707107 │
│ 16   ┆ -0.866025 ┆ -0.5      │
│ 17   ┆ -0.965926 ┆ -0.258819 │
└──────┴───────────┴───────────┘

In [17]:
variables_lag = [
    "intensidad_media",
    "ocupacion_media",
    "velocidad_media"
]

lags = [1, 24, 168]

In [18]:
lag_exprs = []

for variable in variables_lag:
    for lag in lags:
        lag_exprs.append(
            pl.col(variable)
            .shift(lag)
            .over("id_sensor")
            .alias(f"{variable}_lag_{lag}")
        )

df = df.with_columns(lag_exprs)

In [19]:
df.select([
    "ocupacion_media",
    "ocupacion_media_lag_1",
    "ocupacion_media_lag_24",
    "ocupacion_media_lag_168"
]).head(10)

shape: (10, 4)
┌─────────────────┬───────────────────────┬────────────────────────┬─────────────────────────┐
│ ocupacion_media ┆ ocupacion_media_lag_1 ┆ ocupacion_media_lag_24 ┆ ocupacion_media_lag_168 │
│ ---             ┆ ---                   ┆ ---                    ┆ ---                     │
│ f64             ┆ f64                   ┆ f64                    ┆ f64                     │
╞═════════════════╪═══════════════════════╪════════════════════════╪═════════════════════════╡
│ 0.0             ┆ null                  ┆ null                   ┆ null                    │
│ 0.0             ┆ 0.0                   ┆ null                   ┆ null                    │
│ 0.0             ┆ 0.0                   ┆ null                   ┆ null                    │
│ 0.0             ┆ 0.0                   ┆ null                   ┆ null                    │
│ 0.0             ┆ 0.0                   ┆ null                   ┆ null                    │
│ 0.0             ┆ 0.0                   ┆ null                   ┆ null                    │
│ 0.0             ┆ 0.0                   ┆ null                   ┆ null                    │
│ 0.0             ┆ 0.0                   ┆ null                   ┆ null                    │
│ 0.0             ┆ 0.0                   ┆ null                   ┆ null                    │
│ 0.0             ┆ 0.0                   ┆ null                   ┆ null                    │
└─────────────────┴───────────────────────┴────────────────────────┴─────────────────────────┘

In [20]:
rolling_exprs = [

    # Intensidad
    pl.col("intensidad_media")
    .rolling_mean(window_size=3)
    .over("id_sensor")
    .alias("rolling_intensidad_mean_3"),

    pl.col("intensidad_media")
    .rolling_mean(window_size=24)
    .over("id_sensor")
    .alias("rolling_intensidad_mean_24"),

    pl.col("intensidad_media")
    .rolling_std(window_size=24)
    .over("id_sensor")
    .alias("rolling_intensidad_std_24"),


    # Ocupación
    pl.col("ocupacion_media")
    .rolling_mean(window_size=3)
    .over("id_sensor")
    .alias("rolling_ocupacion_mean_3"),

    pl.col("ocupacion_media")
    .rolling_mean(window_size=24)
    .over("id_sensor")
    .alias("rolling_ocupacion_mean_24"),

    pl.col("ocupacion_media")
    .rolling_std(window_size=24)
    .over("id_sensor")
    .alias("rolling_ocupacion_std_24"),

]

df = df.with_columns(rolling_exprs)

In [21]:
df.select([
    "ocupacion_media",
    "rolling_ocupacion_mean_3",
    "rolling_ocupacion_mean_24",
    "rolling_ocupacion_std_24"
]).head(10)

shape: (10, 4)
┌─────────────────┬──────────────────────────┬──────────────────────────┬──────────────────────────┐
│ ocupacion_media ┆ rolling_ocupacion_mean_3 ┆ rolling_ocupacion_mean_2 ┆ rolling_ocupacion_std_24 │
│ ---             ┆ ---                      ┆ 4                        ┆ ---                      │
│ f64             ┆ f64                      ┆ ---                      ┆ f64                      │
│                 ┆                          ┆ f64                      ┆                          │
╞═════════════════╪══════════════════════════╪══════════════════════════╪══════════════════════════╡
│ 0.0             ┆ null                     ┆ null                     ┆ null                     │
│ 0.0             ┆ null                     ┆ null                     ┆ null                     │
│ 0.0             ┆ 0.0                      ┆ null                     ┆ null                     │
│ 0.0             ┆ 0.0                      ┆ null                     ┆ null                     │
│ 0.0             ┆ 0.0                      ┆ null                     ┆ null                     │
│ 0.0             ┆ 0.0                      ┆ null                     ┆ null                     │
│ 0.0             ┆ 0.0                      ┆ null                     ┆ null                     │
│ 0.0             ┆ 0.0                      ┆ null                     ┆ null                     │
│ 0.0             ┆ 0.0                      ┆ null                     ┆ null                     │
│ 0.0             ┆ 0.0                      ┆ null                     ┆ null                     │
└─────────────────┴──────────────────────────┴──────────────────────────┴──────────────────────────┘

In [22]:
df = df.with_columns([

    # Intensidad
    (
        pl.col("intensidad_media")
        - pl.col("intensidad_media_lag_1")
    ).alias("delta_intensidad_1"),

    (
        pl.col("intensidad_media")
        - pl.col("intensidad_media_lag_24")
    ).alias("delta_intensidad_24"),

    # Ocupación
    (
        pl.col("ocupacion_media")
        - pl.col("ocupacion_media_lag_1")
    ).alias("delta_ocupacion_1"),

    (
        pl.col("ocupacion_media")
        - pl.col("ocupacion_media_lag_24")
    ).alias("delta_ocupacion_24"),

])

In [23]:
df.select([
    "ocupacion_media",
    "ocupacion_media_lag_1",
    "delta_ocupacion_1",
    "ocupacion_media_lag_24",
    "delta_ocupacion_24"
]).head(10)

shape: (10, 5)
┌─────────────────┬────────────────────┬───────────────────┬───────────────────┬───────────────────┐
│ ocupacion_media ┆ ocupacion_media_la ┆ delta_ocupacion_1 ┆ ocupacion_media_l ┆ delta_ocupacion_2 │
│ ---             ┆ g_1                ┆ ---               ┆ ag_24             ┆ 4                 │
│ f64             ┆ ---                ┆ f64               ┆ ---               ┆ ---               │
│                 ┆ f64                ┆                   ┆ f64               ┆ f64               │
╞═════════════════╪════════════════════╪═══════════════════╪═══════════════════╪═══════════════════╡
│ 0.0             ┆ null               ┆ null              ┆ null              ┆ null              │
│ 0.0             ┆ 0.0                ┆ 0.0               ┆ null              ┆ null              │
│ 0.0             ┆ 0.0                ┆ 0.0               ┆ null              ┆ null              │
│ 0.0             ┆ 0.0                ┆ 0.0               ┆ null              ┆ null              │
│ 0.0             ┆ 0.0                ┆ 0.0               ┆ null              ┆ null              │
│ 0.0             ┆ 0.0                ┆ 0.0               ┆ null              ┆ null              │
│ 0.0             ┆ 0.0                ┆ 0.0               ┆ null              ┆ null              │
│ 0.0             ┆ 0.0                ┆ 0.0               ┆ null              ┆ null              │
│ 0.0             ┆ 0.0                ┆ 0.0               ┆ null              ┆ null              │
│ 0.0             ┆ 0.0                ┆ 0.0               ┆ null              ┆ null              │
└─────────────────┴────────────────────┴───────────────────┴───────────────────┴───────────────────┘

In [24]:
df = df.with_columns(
    pl.col("ocupacion_media")
    .shift(-1)
    .over("id_sensor")
    .alias("target")
)

In [25]:
df.select([
    "fecha_hora",
    "ocupacion_media",
    "target"
]).head(10)

shape: (10, 3)
┌─────────────────────┬─────────────────┬────────┐
│ fecha_hora          ┆ ocupacion_media ┆ target │
│ ---                 ┆ ---             ┆ ---    │
│ datetime[μs]        ┆ f64             ┆ f64    │
╞═════════════════════╪═════════════════╪════════╡
│ 2026-03-04 13:00:00 ┆ 0.0             ┆ 0.0    │
│ 2026-03-04 14:00:00 ┆ 0.0             ┆ 0.0    │
│ 2026-03-04 15:00:00 ┆ 0.0             ┆ 0.0    │
│ 2026-03-04 16:00:00 ┆ 0.0             ┆ 0.0    │
│ 2026-03-04 17:00:00 ┆ 0.0             ┆ 0.0    │
│ 2026-03-04 18:00:00 ┆ 0.0             ┆ 0.0    │
│ 2026-03-04 19:00:00 ┆ 0.0             ┆ 0.0    │
│ 2026-03-04 20:00:00 ┆ 0.0             ┆ 0.0    │
│ 2026-03-04 21:00:00 ┆ 0.0             ┆ 0.0    │
│ 2026-03-04 22:00:00 ┆ 0.0             ┆ 0.0    │
└─────────────────────┴─────────────────┴────────┘

In [26]:
(
    df
    .null_count()
    .transpose(include_header=True)
    .filter(pl.col("column_0") > 0)
)

shape: (20, 2)
┌──────────────────────────┬──────────┐
│ column                   ┆ column_0 │
│ ---                      ┆ ---      │
│ str                      ┆ u32      │
╞══════════════════════════╪══════════╡
│ intensidad_media_lag_1   ┆ 4933     │
│ intensidad_media_lag_24  ┆ 118368   │
│ intensidad_media_lag_168 ┆ 826568   │
│ ocupacion_media_lag_1    ┆ 4933     │
│ ocupacion_media_lag_24   ┆ 118368   │
│ …                        ┆ …        │
│ delta_intensidad_1       ┆ 4933     │
│ delta_intensidad_24      ┆ 118368   │
│ delta_ocupacion_1        ┆ 4933     │
│ delta_ocupacion_24       ┆ 118368   │
│ target                   ┆ 4933     │
└──────────────────────────┴──────────┘

In [27]:
filas_antes = df.height

df = df.drop_nulls()

filas_despues = df.height

print(f"Filas iniciales: {filas_antes:,}")
print(f"Filas finales: {filas_despues:,}")
print(f"Filas eliminadas: {filas_antes - filas_despues:,}")

Filas iniciales: 40,521,392
Filas finales: 39,689,909
Filas eliminadas: 831,483

In [28]:
df = df.drop([
    "id_fecha",
    "nombre_mes"
])

In [29]:
print(df.shape)

(39689909, 49)

In [30]:
df.head()

shape: (5, 49)
┌───────────┬──────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────┐
│ id_sensor ┆ hora ┆ intensidad_ ┆ intensidad_ ┆ … ┆ delta_inte ┆ delta_ocup ┆ delta_ocup ┆ target │
│ ---       ┆ ---  ┆ media       ┆ max         ┆   ┆ nsidad_24  ┆ acion_1    ┆ acion_24   ┆ ---    │
│ i32       ┆ i32  ┆ ---         ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ f64    │
│           ┆      ┆ f64         ┆ f64         ┆   ┆ f64        ┆ f64        ┆ f64        ┆        │
╞═══════════╪══════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════╡
│ 1001      ┆ 13   ┆ 0.0         ┆ 0.0         ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0    │
│ 1001      ┆ 14   ┆ 0.0         ┆ 0.0         ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0    │
│ 1001      ┆ 15   ┆ 0.0         ┆ 0.0         ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0    │
│ 1001      ┆ 16   ┆ 0.0         ┆ 0.0         ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0    │
│ 1001      ┆ 17   ┆ 0.0         ┆ 0.0         ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0    │
└───────────┴──────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────┘

In [31]:
df.describe()

shape: (9, 50)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ id_sensor ┆ hora      ┆ intensida ┆ … ┆ delta_int ┆ delta_ocu ┆ delta_ocu ┆ target   │
│ ---       ┆ ---       ┆ ---       ┆ d_media   ┆   ┆ ensidad_2 ┆ pacion_1  ┆ pacion_24 ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆ ---       ┆   ┆ 4         ┆ ---       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆ f64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆          │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3.9689909 ┆ 3.9689909 ┆ 3.9689909 ┆ … ┆ 3.9689909 ┆ 3.9689909 ┆ 3.9689909 ┆ 3.968990 │
│           ┆ e7        ┆ e7        ┆ e7        ┆   ┆ e7        ┆ e7        ┆ e7        ┆ 9e7      │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 6792.9544 ┆ 11.519641 ┆ 334.25593 ┆ … ┆ 0.086635  ┆ 0.000245  ┆ 0.003907  ┆ 5.23683  │
│           ┆ 64        ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 2676.7498 ┆ 6.916985  ┆ 576.70247 ┆ … ┆ 220.51604 ┆ 4.224211  ┆ 5.222426  ┆ 9.315551 │
│           ┆ 86        ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1001.0    ┆ 0.0       ┆ 0.0       ┆ … ┆ -89937.25 ┆ -100.0    ┆ -100.0    ┆ 0.0      │
│ 25%       ┆ 4693.0    ┆ 6.0       ┆ 47.5      ┆ … ┆ -21.25    ┆ -0.75     ┆ -0.75     ┆ 0.5      │
│ 50%       ┆ 5989.0    ┆ 12.0      ┆ 150.5     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 2.25     │
│ 75%       ┆ 10109.0   ┆ 18.0      ┆ 387.5     ┆ … ┆ 20.75     ┆ 0.5       ┆ 0.666667  ┆ 5.75     │
│ max       ┆ 11538.0   ┆ 23.0      ┆ 91368.333 ┆ … ┆ 90220.75  ┆ 100.0     ┆ 100.0     ┆ 100.0    │
│           ┆           ┆           ┆ 333       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [32]:
print("=" * 60)
print("FEATURE ENGINEERING COMPLETADO")
print("=" * 60)

print(f"Filas finales: {df.height:,}")
print(f"Columnas finales: {df.width}")
print(f"Sensores únicos: {df['id_sensor'].n_unique():,}")

print("\nEl dataset incluye:")
print("- Variables temporales originales")
print("- Variables temporales cíclicas")
print("- Variables lag")
print("- Variables rolling")
print("- Variables de tendencia")
print("- Variable objetivo (target)")

============================================================
FEATURE ENGINEERING COMPLETADO
============================================================
Filas finales: 39,689,909
Columnas finales: 49
Sensores únicos: 4,915

El dataset incluye:
- Variables temporales originales
- Variables temporales cíclicas
- Variables lag
- Variables rolling
- Variables de tendencia
- Variable objetivo (target)

In [33]:
df.write_parquet("../data/modeling/features.parquet")

print("Feature engineering completado correctamente.")

Feature engineering completado correctamente.